sudo: required

env:
  PKG_NAME=robot-framework-coe

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --squash -t devops_coe_robot:ci .
  
deploy:
  skip_cleanup: true
  provider: script
  script: bash docker_push
  on:
    branch: main
